config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/auth/twitter/callback' => "omniauth_callbacks#twitter"

  resources :accounts do
    member do
      patch :update_status
    end
  end
  resources :targets
  resources :histories, only: [:index]
  resources :message_patterns, only: [:new, :edit, :create, :update] do
    resources :direct_messages, only: [:new]
  end
  resources :direct_messages, only: [:index, :edit, :create, :update]
  resources :sent_messages, only: [:index]

  resources :groups, only: [:new, :edit, :create, :update] do
    patch :change_order
    member do
      get :new_accounts
      post :create_accounts
    end
  end

  resources :settings, only: [:edit, :update]

end

app/models/direct_message.rb
# == Schema Information
#
# Table name: direct_messages
#
#  id                 :integer          not null, primary key
#  message_pattern_id :integer
#  text               :string(255)
#  step               :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class DirectMessage < ActiveRecord::Base
  belongs_to :message_pattern
  has_many :sent_messages
end

app/controllers/direct_messages_controller.rb
# == Schema Information
#
# Table name: direct_messages
#
#  id                 :integer          not null, primary key
#  message_pattern_id :integer
#  text               :string(255)
#  step               :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class DirectMessagesController < ApplicationController
  permits :message_pattern_id, :step, :text

  def index
    @message_patterns = MessagePattern.includes(:direct_messages)
  end

  def new(message_pattern_id)
    @direct_message = DirectMessage.new(message_pattern_id: message_pattern_id.to_i)
  end

  def edit(id)
    @direct_message = DirectMessage.find(id)
  end

  def create(direct_message)
    @direct_message = DirectMessage.new(direct_message)

    if @direct_message.save
      redirect_to direct_messages_path
    else
      render :new
    end
  end

  def update(id, direct_message)
    @direct_message = DirectMessage.find(id)

    if @direct_message.update(direct_message)
      redirect_to direct_messages_path
    else
      render :edit
    end
  end
end

app/views/direct_messages/_direct_message.html.slim
- cache(direct_message) do
  tr.direct_message data-direct-message-id=direct_message.id
    td.step                = direct_message.step
    td.text                = direct_message.text
    td.edit_direct_message = link_to 'Edit', edit_direct_message_path(direct_message), class:'btn btn-warning'

app/views/direct_messages/_form.html.slim
= simple_form_for(@direct_message) do |f|

  .form-inputs
    = f.hidden_field :message_pattern_id
    = f.input :step
    = f.input :text

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/direct_messages/edit.html.slim
h1 Edit Direct Message

== render 'form'

app/views/direct_messages/index.html.slim
ul.nav.nav-tabs
  - @message_patterns.each_with_index do |pattern, i|
    - if i == 0
      li.active
        a href="#tab#{pattern.id}" data-toggle="tab" = pattern.title
    - else
      li
        a href="#tab#{pattern.id}" data-toggle="tab" = pattern.title
  / タブの追加ボタン
  li.unsortable data-group-id=0
    = link_to '+', new_message_pattern_path

.tab-content
  - @message_patterns.each_with_index do |pattern, i|
    = tab_pane(i, {id: "tab#{pattern.id}"}) do
      = link_to 'パターンの編集', edit_message_pattern_path(pattern)
      table.table
        thead
          tr
            th Step
            th Text
            th
            th
        tbody
          = render pattern.direct_messages
      .mt10
        = link_to "DMの追加", new_message_pattern_direct_message_path(pattern)

app/views/direct_messages/new.html.slim
h1 New Direct Message

== render 'form'