config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/auth/twitter/callback' => "omniauth_callbacks#twitter"

  resources :accounts do
    member do
      patch :update_status
    end
  end
  resources :targets
  resources :histories, only: [:index]
  resources :message_patterns, only: [:new, :edit, :create, :update] do
    resources :direct_messages, only: [:new]
  end
  resources :direct_messages, only: [:index, :edit, :create, :update]
  resources :sent_messages, only: [:index]

  resources :groups, only: [:new, :edit, :create, :update] do
    patch :change_order
    member do
      get :new_accounts
      post :create_accounts
    end
  end

  resources :settings, only: [:edit, :update]

end

app/models/target.rb
# == Schema Information
#
# Table name: targets
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  screen_name :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#

class Target < ActiveRecord::Base
  belongs_to :user

  has_one :account
  has_many :followed_users

  before_validation :remove_at_mark!

  def remove_at_mark!
    self.screen_name.gsub! /\@/, ""
  end

end

app/controllers/targets_controller.rb
# coding: utf-8
# == Schema Information
#
# Table name: targets
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  screen_name :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#


class TargetsController < ApplicationController
  before_action :set_target, only: [:show, :edit, :update, :destroy]
  permits :name, :screen_name

  # GET /targets
  def index
    @targets = Target.all
  end

  # GET /targets/1
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
  end

  # GET /targets/1/edit
  def edit
  end

  # POST /targets
  def create(target)
    @target = Target.new(target)
    @target.user = current_user

    if @target.save
      redirect_to @target, notice: 'Target was successfully created.'
    else
      render :new
    end
  end

  # PUT /targets/1
  def update(target)
    if @target.update(target)
      redirect_to @target, notice: 'Target was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /targets/1
  def destroy
    @target.destroy

    redirect_to targets_url, notice: 'Target was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target(id)
      @target = Target.find(id)
    end
end

app/views/targets/_form.html.slim
= simple_form_for(@target) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :screen_name

  .form-actions
    = f.button :submit

app/views/targets/edit.html.slim
h1 Editing target

== render 'form'

= link_to 'Show', @target
'|
= link_to 'Back', targets_path

app/views/targets/index.html.slim
table.table
  thead
    tr
      th Name
      th Screen name
      th
      th
      th

  tbody
    - @targets.each do |target|
      tr
        td = target.name
        td = target.screen_name
        td = link_to 'Show', target
        td = link_to 'Edit', edit_target_path(target)
        td = link_to 'Destroy', target, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'ターゲットの追加', new_target_path

app/views/targets/new.html.slim
h1 New target

== render 'form'

= link_to 'Back', targets_path

app/views/targets/show.html.slim
p
  strong Name:
  = @target.name
p
  strong Screen name:
  = @target.screen_name

- @target.followed_users.each do |user|
  .followed_user
    = user.created_at.strftime("%m/%d %H:%M")
    span style="margin-left:10px;" 
    -if user.name
      = link_to user.name, "https://twitter.com/#{user.screen_name}", target:'_blank'
    -else
      = user.user_id
= link_to 'Edit', edit_target_path(@target)
'|
= link_to 'Back', targets_path