config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/auth/twitter/callback' => "omniauth_callbacks#twitter"

  resources :accounts do
    member do
      patch :update_status
    end
  end
  resources :targets
  resources :histories, only: [:index]
  resources :message_patterns, only: [:new, :edit, :create, :update] do
    resources :direct_messages, only: [:new]
  end
  resources :direct_messages, only: [:index, :edit, :create, :update]
  resources :sent_messages, only: [:index]

  resources :groups, only: [:new, :edit, :create, :update] do
    patch :change_order
    member do
      get :new_accounts
      post :create_accounts
    end
  end

  resources :settings, only: [:edit, :update]

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @groups = current_user.groups.order(:display_order).includes([{accounts: :target}, :message_pattern])
    @groups = Group.all.order(:display_order).includes([{accounts: :target}, :message_pattern])
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  
end

app/views/welcome/index.html.slim
/ タブリスト
ul.nav.nav-tabs.sortable
  / グループごとにタブの作成
  - @groups.each_with_index do |group, i|
    - if i == 0
      li.active data-group-id=group.id
        a href="#tab#{group.id}" data-toggle="tab" = group.name
    - else
      li data-group-id=group.id
        a href="#tab#{group.id}" data-toggle="tab" = group.name
  / タブの追加ボタン
  li.unsortable data-group-id=0
    = link_to '+', new_group_path

.tab-content
  / 現在のタブの内容を表示（アカウントリスト）
  - @groups.each_with_index do |group, i|
    = tab_pane(i, {id: "tab#{group.id}"}) do
      .pattern= "DMパターン: #{group.message_pattern_title}"
      = link_to 'グループの編集', edit_group_path(group)
      = '/'
      = link_to '一括アカウント追加', new_accounts_group_path(group)
      table.table
        thead
          tr
            th ScreenName
            th Target
            th Desc
            th Friends
            th Followers
            th Update
            th Follow
            th Unfollow
            th DM
            th Retweet
            th
        tbody
          = render group.accounts
      .mt10
        = link_to "アカウントの追加", new_account_path(group_id: group.id)
      .mt10
        = link_to 'Twitterでログインしてアカウントを追加', "/auth/twitter?group_id=#{group.id}"