config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  get '/auth/twitter/callback' => "omniauth_callbacks#twitter"

  resources :accounts do
    member do
      patch :update_status
    end
  end
  resources :targets
  resources :histories, only: [:index]
  resources :message_patterns, only: [:new, :edit, :create, :update] do
    resources :direct_messages, only: [:new]
  end
  resources :direct_messages, only: [:index, :edit, :create, :update]
  resources :sent_messages, only: [:index]

  resources :groups, only: [:new, :edit, :create, :update] do
    patch :change_order
    member do
      get :new_accounts
      post :create_accounts
    end
  end

  resources :settings, only: [:edit, :update]

end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Twineuvers
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-fixed-top.header
      .container
        .navbar-header
          = link_to image_tag('logo.png'), :root, class: "navbar-brand"
        .nav.navbar-nav
          = nav_list(controller.controller_name, "welcome") do
            = link_to 'TopPage', root_path
          = nav_list(controller.controller_name, "targets") do
            = link_to 'Targets', targets_path
          = nav_list(controller.controller_name, "histories") do
            = link_to 'Histories', histories_path
          = nav_list(controller.controller_name, "direct_messages") do
            = link_to 'DirectMessages', direct_messages_path
          = nav_list(controller.controller_name, "sent_messages") do
            = link_to 'SentMessages', sent_messages_path
    .main-container
      = yield